# Generated by Django 4.1.13 on 2024-09-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hero_section', '0007_technologysvg_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricings',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('wise', models.CharField(blank=True, help_text='Per Month / Per Year', max_length=255, null=True)),
                ('criteria', models.CharField(blank=True, help_text='Features', max_length=255, null=True)),
                ('button', models.CharField(blank=True, max_length=255, null=True)),
                ('button_link', models.TextField(blank=True, null=True)),
                ('recomended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pricing_plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='pricing.pricingplan')),
            ],
            options={
                'verbose_name': 'Pricing Feature',
                'verbose_name_plural': 'Pricing Features',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
    ]
