# Generated by Django 4.1.13 on 2024-09-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingfeature',
            name='pricing_plans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricingplan'),
        ),
    ]
