# Generated by Django 4.2.16 on 2024-09-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCreateUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroContant',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hero Contant',
                'verbose_name_plural': 'Hero Contants',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
        migrations.CreateModel(
            name='HeroButton',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('button_svg', models.TextField()),
                ('hero_contant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero_section.herocontant')),
            ],
            options={
                'verbose_name': 'Hero Button',
                'verbose_name_plural': 'Hero Buttons',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
    ]
