# Generated by Django 4.2.16 on 2024-09-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobutton',
            name='hero_contant',
        ),
    ]
