# Generated by Django 4.2.16 on 2024-09-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_section', '0002_herobutton_button_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobutton',
            name='button_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
