# Generated by Django 4.2.16 on 2024-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_section', '0002_remove_herobutton_hero_contant'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobutton',
            name='button_svg',
            field=models.TextField(default='new'),
            preserve_default=False,
        ),
    ]
