# Generated by Django 4.2.16 on 2024-09-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_section', '0003_alter_herobutton_button_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobutton',
            name='design_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=10),
        ),
    ]
