# Generated by Django 4.2.16 on 2024-09-06 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero_section', '0004_herobutton_design_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyUses',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('contant', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Technology contant',
                'verbose_name_plural': 'Technology contants',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
        migrations.AddField(
            model_name='herocontant',
            name='image',
            field=models.ImageField(default='', upload_to='hero_section/images'),
        ),
        migrations.CreateModel(
            name='TechnologySvg',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('svg_image', models.TextField(blank=True, null=True)),
                ('contant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero_section.technologyuses')),
            ],
            options={
                'verbose_name': 'Technology SVG',
                'verbose_name_plural': 'Technology SVGs',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
    ]
