# Generated by Django 4.2.16 on 2024-09-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_section', '0005_technologyuses_herocontant_image_technologysvg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herocontant',
            name='image',
            field=models.ImageField(default='', help_text='Image must be 845(W) × 329(H) px', upload_to='hero_section/images'),
        ),
    ]
