# Generated by Django 4.2.16 on 2024-09-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hero_section', '0007_technologysvg_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('name', models.CharField(blank=True, help_text='Name of service like: Feature', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('link_title', models.CharField(blank=True, max_length=255, null=True)),
                ('svg_image', models.TextField(blank=True, null=True)),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature.feature')),
            ],
            options={
                'verbose_name': 'Feature item',
                'verbose_name_plural': 'Feature items',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
    ]
