# Generated by Django 4.1.13 on 2024-09-17 12:22

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hero_section', '0007_technologysvg_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('content', django_quill.fields.QuillField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='about/image')),
                ('abouts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.about')),
            ],
            options={
                'verbose_name': 'About Image',
                'verbose_name_plural': 'About Images',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
        migrations.CreateModel(
            name='AboutButton',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('button_name', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link', models.TextField(blank=True, null=True)),
                ('abouts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.about')),
            ],
            options={
                'verbose_name': 'About Button',
                'verbose_name_plural': 'About Buttons',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
    ]
