# Generated by Django 4.1.13 on 2024-09-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero_section', '0007_technologysvg_link'),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('autocreateupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hero_section.autocreateupdate')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('years', models.IntegerField(default=0)),
                ('abouts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.about')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
            bases=('hero_section.autocreateupdate', models.Model),
        ),
    ]
