# Generated by Django 4.1.13 on 2024-09-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta',
            name='cta_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
